<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6FM5GAH" failures="1" tests="1" name="Test-Runner-2" time="9.13" errors="0" timestamp="2023-10-12T13:49:33 IST">
  <testcase classname="com.organization.ReadMultipleDataProviderTest" name="readmultipledata" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NegativeArraySizeException: -1">
      <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NegativeArraySizeException: -1
at com.GenericUtility.ExcelUtility.readMultipleDataFromExcel(ExcelUtility.java:66)
at com.organization.ReadMultipleDataProviderTest.getData(ReadMultipleDataProviderTest.java:50)
... 19 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- readmultipledata -->
</testsuite> <!-- Test-Runner-2 -->
